### ISSUE TITLE
Error: DoesNotExist at /feedings/add/

### ISSUE THREAD

**Issue by mbaitelman** [babybuddy/babybuddy#114]
Getting this error when running the site using docker. 
Other pages work fine. 

Please let me know if there is any other information I can add. 

It looks like this is related to #37 but was undone and the issue exists again in
https://github.com/babybuddy/babybuddy/blob/master/core/forms.py#L49

```Environment

Request Method: GET
Request URL: http://babybuddy.baitelman.xyz:8000/feedings/add/

Django Version: 3.0.2
Python Version: 3.8.1
Installed Applications:
['api',
 'babybuddy',
 'core',
 'dashboard',
 'reports',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'widget_tweaks',
 'easy_thumbnails',
 'storages',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 85, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 168, in get
    return super().get(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 66, in get_context_data
    kwargs['form'] = self.get_form()
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 33, in get_form
    return form_class(**self.get_form_kwargs())
  File "/app/core/forms.py", line 67, in __init__
    kwargs = set_initial_values(kwargs, type(self))
  File "/app/core/forms.py", line 48, in set_initial_values
    last_feeding = models.Feeding.objects.filter(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 660, in latest
    return self.reverse()._earliest(*fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 654, in _earliest
    return obj.get()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /feedings/add/
Exception Value: Feeding matching query does not exist.```

**Comment by cdubz** [comment]
Are you running a version > 1.3.0? Could you post your `docker-compose.yml` file? That is that exception that was thrown _before_ 60cd90ca80f4771b8b98372368c7b3b38d1563e2 landed. This issue was caused by f7d9f6b361bf154e5468724e3e73f2c5b1f3039f and is present is 1.3.0. It also happens that is the last version available in the _old_ Docker Hub repo... see my note in the latest release, [v1.3.4](https://github.com/babybuddy/babybuddy/releases/tag/v1.3.4). Maybe I need to push one last version without the bug to that old repo...

**Comment by mbaitelman** [comment]
Thank you.
It looks like I pulled the repo before the update and just today started setting it up.
Pulled the latest and tried again and it works perfectly.
