### ISSUE TITLE
Docker instance using Sqlite

### ISSUE THREAD

**Issue by meichthys** [babybuddy/babybuddy#145]
Would i need to build a custom docker image if i wanted to use Sqlite for my backend?
Currently I can't seem to run the existing docker image because it is expecting a postgress backend.

**Comment by cdubz** [comment]
Hmmm, potentially not. As always, I must preface by saying that I don't have a lot of experience with Docker. But I'm thinking this might work as a `docker-compose.yml` config --

```
version: "3.7"
services:
APP
    volumes:
      - db:/db-data:rw
  app:
    image: babybuddy/babybuddy
    environment:
      - ALLOWED_HOSTS=<PUT SOMETHING HERE>
      - DJANGO_SETTINGS_MODULE=babybuddy.settings.production.example
      - SECRET_KEY=<PUT SOMETHING HERE>
      - DEBUG=False
    volumes:
      - media:/app/media:rw
    # Sleep 5 seconds to allow the db to to come up;
    command: bash -c 'sleep 5 && python manage.py migrate --noinput && python manage.py createcachetable && gunicorn babybuddy.wsgi -b :8000 --log-level=info'
    ports:
      - "8000:8000"
volumes:
  media: {}
```

Note: this uses the [`production.example.py` settings file](https://github.com/babybuddy/babybuddy/blob/master/babybuddy/settings/production.example.py), which is not really meant for direct use. But this is only necessary because the [`base.py` settings file](https://github.com/babybuddy/babybuddy/blob/master/babybuddy/settings/base.py) does not set the `DATABASES` setting. Maybe it should...

Let me know if this works for you.

**Comment by meichthys** [comment]
@cdubz Thanks for the suggestion! It doesn't seem to be working though. It throws the following error despite using `- DJANGO_SETTINGS_MODULE=babybuddy.settings.production.example`
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 341, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 225, in close_all
    for alias in self:
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 219, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'babybuddy.settings.production'
```

**Comment by cdubz** [comment]
Yeah, I was afraid of that. I think the fact that the production file has `.example.py` messes it up... the `DATABASES` variable would need to be added to the base config for this to work. And I imagine some changes to `MEDIA_ROOT` might be needed as well. I'll take look when I can, although I can't guarantee this will be any time soon -- I'm not sure if _just_ the config change would make this possible or if Docker would need something more.

**Comment by meichthys** [comment]
No problem. I’ll play around myself if I get some time. If I get something working I’ll report back or submit a pull request.

**Comment by cdubz** [comment]
@meichthys I pushed a change this morning that moves the `DATABASES` config to the base settings so this might work now if you change the Docker compose `DJANGO_SETTINGS_MODULE` env setting to `babybuddy.settings.base` but I also just realized the default location will not be rw for Docker so this simple change won’t really be enough.

**Comment by cdubz** [comment]
:wave: @meichthys I just pushed a few more changes that should do the job. There is now a `docker-compose.example.sqlite.yml` file in the repo with config for a SQLite-based Docker Compose setup.

**Comment by meichthys** [comment]
Thanks! I'm still hitting an issue when starting up the docker container. The container fails to start and logs the following:

```
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/app/babybuddy/management/commands/migrate.py", line 10, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/app/babybuddy/management/commands/migrate.py", line 10, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exce
```

**Comment by cdubz** [comment]
Hmmm. That sounds like it’s not using the updated base settings file. Can you post your whole docker-compose.yml file?

**Comment by meichthys** [comment]
Here's my docker-compose... It could be that when i re-deployed my docker-compose file it didn't pull the new image. I'll check on that..
```
version: "3"
services:
  #Babybuddy Sqlite
  babybuddy:
    image: babybuddy/babybuddy
    # See Babybuddy README.md#configuration for other environment configuration$
    environment:
      - ALLOWED_HOSTS=*
      - DJANGO_SETTINGS_MODULE=babybuddy.settings.base
      - SECRET_KEY=my_super_secret_key_that_has been_changed_for_github
      - TIME_ZONE=
      - DEBUG=False # Turn to False in production
    volumes:
      - babybuddy_data:/app/data:rw
      - babybuddy_media:/app/media:rw
    command: bash -c 'python manage.py migrate --noinput && python manage.py cr$
    ports:
      - "8000:8000"

volumes:
  #babybuddy
  babybuddy_data:
  babybuddy_media:
```

**Comment by cdubz** [comment]
Yeah that looks right. I only tested locally. I’ll test from the hub image when I get a chance.

**Comment by meichthys** [comment]
After force-pulling the latest docker image, its working as expected! 
I didn't realize that `docker-compose up` doesn't fetch the latest image from docker hub.
Should be all set! Thanks for making changes to make Sqlite work! It's definitely more maintainable and a much leaner setup for a single two-user instance. 🚀
