### ISSUE TITLE
Unable to run on docker ARM64

### ISSUE THREAD

**Issue by markus-seidl** [babybuddy/babybuddy#199]
I've tried to run the docker-compose.yml on an ARM64 device, but got 'Invalid exec format' upon startup.

The system is:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

```
$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1296.0000
CPU min MHz:         408.0000
BogoMIPS:            48.00
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32
```

After that I've tried building the image myself. This can be "easily" done with a modification of the docker-compose.yaml (leaving this here for others, if needed. Checkout the code into ./code ):

```
# ...
  app:
    image: babybuddy-arm64
    build:
      context: ./code/
# ...
```

Unfortunately, this yields the following error upon executing ```docker-compose build```

```
⠹ Locking..✘ Locking Failed!
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /root/.local/share/virtualenvs/app-4PlAip0Q/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-axapuy0r/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-axapuy0r/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-resolver-axapuy0r/psycopg2/pip-egg-info
     cwd: /tmp/pip-resolver-axapuy0r/psycopg2/
Complete output (14 lines):
running egg_info
creating /tmp/pip-resolver-axapuy0r/psycopg2/pip-egg-info/psycopg2.egg-info
writing /tmp/pip-resolver-axapuy0r/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
writing dependency_links to /tmp/pip-resolver-axapuy0r/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
writing top-level names to /tmp/pip-resolver-axapuy0r/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
writing manifest file '/tmp/pip-resolver-axapuy0r/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'
Error: pg_config executable not found.

Please add the directory containing pg_config to the PATH
or specify the full executable path with the option:

    python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.
----------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils.py", line 1395, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 350, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 287, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 538, in _generate_metadata
    return generate_metadata_legacy(
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/build/metadata_legacy.py", line 115, in generate_metadata
    call_subprocess(
  File "/usr/local/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pipenv.patched.notpip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I don't know the Dependencies enough to help myself through this error. Maybe someone has a suggestion (or maybe a different path?)

Thanks!

**Comment by markus-seidl** [comment]
I've got it running with 

Dockerfile
```
FROM python:3.8-alpine as app
ENV PYTHONUNBUFFERED 1

RUN apk add postgresql-dev
RUN apk --update add libxml2-dev libxslt-dev libffi-dev gcc musl-dev libgcc openssl-dev curl
RUN apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev

RUN pip install --upgrade pipenv gunicorn
WORKDIR /app
COPY Pipfile /app/
RUN pipenv lock
RUN pipenv install --deploy --system
ADD manage.py /app/
ADD api /app/api
ADD babybuddy /app/babybuddy
ADD core /app/core
ADD dashboard /app/dashboard
ADD locale /app/locale
ADD reports /app/reports
ADD static /app/static
ADD etc/gunicorn.py /app/
```

No bash in Alpine by default, so this docker-compose.yml change is necessary:

```
    # Sleep 5 seconds to allow the db to to come up;
    command: sh -c 'sleep 5 && python manage.py migrate --noinput && python manage.py createcachetable && gunicorn babybuddy.wsgi -b :8000 --log-level=info'
```

I don't know if this is the intended or best way to do this.

**Comment by cdubz** [comment]
Thanks for the notes. I will take a look at this when I can to see if there are any changes we can make to the committed Dockerfile to improve this experience.

ARM has always been a bit of a problem with this package for various reasons ([see some other previous issues](https://github.com/babybuddy/babybuddy/issues?q=Arm)).  I was hoping that the relatively recent dropping of the Pandas requirement and removal of the lock file would help but maybe this is just always going to be tricky.

I wonder if there is some approach to having a consistent separate build for ARM...

**Comment by philip-n** [comment]
There is a multi-architecture docker image by @nicholaswilde, see https://github.com/nicholaswilde/docker-babybuddy . Maybe his repo or the author can help out with some information?

**Comment by cdubz** [comment]
@markus-seidl another thing to try -- LSIO has put together a new image build process for Baby Buddy that includes ARM builds. After some testing and documentation adjustments I intend to make this the "official" way to use Baby Buddy with Docker: https://github.com/linuxserver/docker-babybuddy
