### ISSUE TITLE
unsupported format character in "duration_string" (i18n problem, german language)

### ISSUE THREAD

**Issue by BenjaminHae** [babybuddy/babybuddy#208]
I'm using v1.5.1 (docker) and currently get the following error  message whenever I query the sleep pattern in german language:
```
Internal Server Error: /children/XXXX/reports/sleep/pattern/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/app/reports/views.py", line 131, in get_context_data
    context['html'], context['js'] = graphs.sleep_pattern(instances)
  File "/app/reports/graphs/sleep_pattern.py", line 78, in sleep_pattern
    labels[start_date].append(_format_label(duration, start_time,
  File "/app/reports/graphs/sleep_pattern.py", line 171, in _format_label
    duration_string(duration),
  File "/app/core/utils.py", line 15, in duration_string
    duration = ngettext('%(hours)s hour', '%(hours)s hours', h) % {
ValueError: unsupported format character 'S' (0x53) at index 9
```

Additionally, the duration field is empty in any list that contains a duration.

It works however when I set my language to english. So I guess it's an i18n problem.

**Comment by cdubz** [comment]
That would be here: https://github.com/babybuddy/babybuddy/blob/master/locale/de/LC_MESSAGES/django.po#L1368-L1372

I think the two `msgstr` entries there just need to be changed to `%(hours)s`... I can never remember how that works exactly.
