### ISSUE TITLE
`gulp migrate` failing in Gitpod

### ISSUE THREAD

**Issue by cdubz** [babybuddy/babybuddy#320]
Starting a new Gitpod environment is resulting in -- 

```
[15:15:56] Using gulpfile /workspace/babybuddy/gulpfile.js
[15:15:56] Starting 'migrate'...
Traceback (most recent call last):
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 86, in wrapped
    saved_locale = translation.get_language()
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 254, in get_language
    return _trans.get_language()
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 57, in __getattr__
    if settings.USE_I18N:
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '"babybuddy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/workspace/babybuddy/.venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '"babybuddy'
[15:15:57] 'migrate' errored after 1.08 s
[15:15:57] Error: 1
    at formatError (/home/gitpod/.nvm/versions/node/v16.11.0/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/home/gitpod/.nvm/versions/node/v16.11.0/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (node:events:402:35)
    at Gulp.emit (node:domain:475:12)
    at Object.error (/workspace/babybuddy/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/workspace/babybuddy/node_modules/now-and-later/lib/map.js:50:14)
    at f (/workspace/babybuddy/node_modules/once/once.js:25:25)
    at f (/workspace/babybuddy/node_modules/once/once.js:25:25)
    at tryCatch (/workspace/babybuddy/node_modules/async-done/index.js:24:15)
    at ChildProcess.done (/workspace/babybuddy/node_modules/async-done/index.js:40:12)
```

when running the `gulp migrate` command. The relevant error there is `ModuleNotFoundError: No module named '"babybuddy'`. This definitely worked before and as far as I know nothing has changed with the Gitpod config.

Running `env` in Gitpod after a failed setup shows `DJANGO_SETTINGS_MODULE="babybuddy.settings.development"`. Running `export DJANGO_SETTINGS_MODULE=babybuddy.settings.development` resolves the issue as `gulp migrate` works and the `env` output is now `DJANGO_SETTINGS_MODULE=babybuddy.settings.development`.

The [`.gitpod.yml`](https://github.com/babybuddy/babybuddy/blob/master/.gitpod.yml) file does not contain the double quotes so I'm not quite sure what to try to address this.

@lutzky, any ideas?

**Comment by Alberdi** [comment]
It seems like an already-fixed-not-yet-deployed issue in GitPod: https://github.com/gitpod-io/gitpod/issues/5887
So waiting might be enough!

**Comment by lutzky** [comment]
Ha, great minds!

**Comment by cdubz** [comment]
Nice catch! Thank you both for posting this out.
