### ISSUE TITLE
Crashes on startup: `ImportError: cannot import name 'etree' from 'lxml'`

### ISSUE THREAD

**Issue by vrutkovs** [babybuddy/babybuddy#336]
BabyBaby running from https://github.com/linuxserver/docker-babybuddy/pkgs/container/babybuddy/10232596?tag=1.9.1 crashes on startup:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/easy_thumbnails/templatetags/easy_thumbnails_tags.py", line 8, in <module>
    from .thumbnail import *
  File "/usr/lib/python3.9/site-packages/easy_thumbnails/templatetags/thumbnail.py", line 12, in <module>
    from easy_thumbnails.files import get_thumbnailer
  File "/usr/lib/python3.9/site-packages/easy_thumbnails/files.py", line 17, in <module>
    from easy_thumbnails.VIL.Image import load
  File "/usr/lib/python3.9/site-packages/easy_thumbnails/VIL/Image.py", line 10, in <module>
    from svglib.svglib import svg2rlg
  File "/usr/lib/python3.9/site-packages/svglib/svglib.py", line 39, in <module>
    from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' (/usr/lib/python3.9/site-packages/lxml/__init__.py)
```

**Comment by cdubz** [comment]
Thanks for reporting. I’ll give this a test when I can. I only just added Python 3.9 testing and it passed tests and worked fine in my local testing 🤔

**Comment by AhmetCelikbasBMX** [comment]
@cdubz Thank you for your support. This bug also affect me. Here is the traceback :
```
Django Version: 3.2.9
Python Version: 3.9.5
Installed Applications:
['api',
 'babybuddy',
 'core',
 'dashboard',
 'reports',
 'axes',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'widget_tweaks',
 'easy_thumbnails',
 'storages',
 'import_export',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'babybuddy.middleware.RollingSessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'babybuddy.middleware.UserTimezoneMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'babybuddy.middleware.UserLanguageMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'axes.middleware.AxesMiddleware']



Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]

During handling of the above exception ('django'), another exception occurred:
  File "/usr/lib/python3.9/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    <source code not available>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    <source code not available>
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    <source code not available>
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    <source code not available>
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
    <source code not available>
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    <source code not available>
  File "/usr/lib/python3.9/site-packages/easy_thumbnails/templatetags/easy_thumbnails_tags.py", line 8, in <module>
    from .thumbnail import *
  File "/usr/lib/python3.9/site-packages/easy_thumbnails/templatetags/thumbnail.py", line 12, in <module>
    from easy_thumbnails.files import get_thumbnailer
  File "/usr/lib/python3.9/site-packages/easy_thumbnails/files.py", line 17, in <module>
    from easy_thumbnails.VIL.Image import load
  File "/usr/lib/python3.9/site-packages/easy_thumbnails/VIL/Image.py", line 10, in <module>
    from svglib.svglib import svg2rlg
  File "/usr/lib/python3.9/site-packages/svglib/svglib.py", line 39, in <module>
    from lxml import etree

The above exception (cannot import name 'etree' from 'lxml' (/usr/lib/python3.9/site-packages/lxml/__init__.py)) was the direct cause of the following exception:
  File "/usr/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/lib/python3.9/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/lib/python3.9/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/lib/python3.9/site-packages/django/template/loader.py", line 38, in select_template
    engines = _engine_list(using)
  File "/usr/lib/python3.9/site-packages/django/template/loader.py", line 66, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/usr/lib/python3.9/site-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/usr/lib/python3.9/site-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/usr/lib/python3.9/site-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/usr/lib/python3.9/site-packages/django/template/backends/django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/usr/lib/python3.9/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/usr/lib/python3.9/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/usr/lib/python3.9/site-packages/django/template/backends/django.py", line 123, in get_package_libraries
    raise InvalidTemplateLibrary(

Exception Type: InvalidTemplateLibrary at /children/selin-celikbas/dashboard/
Exception Value: Invalid template library specified. ImportError raised when trying to load 'easy_thumbnails.templatetags.easy_thumbnails_tags': cannot import name 'etree' from 'lxml' (/usr/lib/python3.9/site-packages/lxml/__init__.py)

```

**Comment by cdubz** [comment]
Until I get a chance to look at this — there are a number of references to similar issues. Could one of you try the recommendation here? https://github.com/WeblateOrg/weblate/issues/4183#issuecomment-953697959

**Comment by vrutkovs** [comment]
Ah, apparently its a dependency problem. `lxml` installed from pip cannot be linked properly to alpine's python (ldd throws a lot of "symbol not found"). Installing `py3-lxml` fixes it

**Comment by jcgoette** [comment]
Who manages the Dockerfile? babybuddy or LSIO?

**Comment by cdubz** [comment]
LSIO supports us here. I think https://github.com/linuxserver/docker-babybuddy/pull/10 is the correct fix here but it looks like it needs some additional dev packages?

**Comment by cdubz** [comment]
This should be resolved by https://github.com/linuxserver/docker-babybuddy/pull/12 -- thanks to LSIO crew!
