### ISSUE TITLE
Sleep Patterns showing a 500 error - Exception Type: KeyError

### ISSUE THREAD

**Issue by JoeArcher007** [babybuddy/babybuddy#417]
I'm using the LSIO Docker version of Baby Buddy, but I believe this fits here more than there, though will readily move the bug to there if deemed as such.

Ubuntu 21.10 Host
Docker image: Babybuddy v1.10.2-ls27 (LSIO)

When I go to run a Sleep Pattern report, it give's the 500 server error.  Turned on Debug and this is what is happening:
```
Environment:

Request Method: GET
Request URL: https://my.domain.ca/children/child/reports/sleep/pattern/

Django Version: 4.0.2
Python Version: 3.9.5
Installed Applications:
['api',
 'babybuddy',
 'core',
 'dashboard',
 'reports',
 'axes',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'widget_tweaks',
 'imagekit',
 'storages',
 'import_export',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'babybuddy.middleware.RollingSessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'babybuddy.middleware.UserTimezoneMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'babybuddy.middleware.UserLanguageMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'axes.middleware.AxesMiddleware']

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/app/babybuddy/reports/views.py", line 141, in get_context_data
    context["html"], context["js"] = graphs.sleep_pattern(instances)
  File "/app/babybuddy/reports/graphs/sleep_pattern.py", line 69, in sleep_pattern
    days[start_date].append(

Exception Type: KeyError at /children/child/reports/sleep/pattern/
Exception Value: '2021-12-14'
```

Not too sure if others are experiencing something similar or if it's something on my own. Initially I had thought it was to do with time zone issues, but that doesn't appear to be it from what I can tell.

**Comment by cdubz** [comment]
Hm yeah my first guess #174 but this looks potentially different...

**Comment by JoeArcher007** [comment]
I can confirm, when I change my user account settings to be UTC, the sleep patterns works correctly. So _it is_ to do with the users time zone affecting the sleep patterns script. All other reports seem to be OK at this time when using a time zone (specifically for me, it's America/Toronto)

**Comment by cdubz** [comment]
Sigh. Ok. I was kind of hoping it was something else, haha. I still have not had a chance to try to dig in to why this happens and there was some recent refactoring of the sleep graph code that I hoped might magically fix it. But no luck 😆

**Comment by cdubz** [comment]
No progress yet 😞 Closing this as a duplicate of #174 -- the workaround is to fudge any entries that have a date bound a time effected by daylight savings.
