### ISSUE TITLE
Add a way to set the SMTP configuration

### ISSUE THREAD

**Issue by gardncol** [babybuddy/babybuddy#499]
As a babybuddy admin I need a way to send password reset emails so that I can recover if I or other users lose access to the service.

I would like a way to set the SMTP values with the Docker installation. This would allow the password recovery to function after proper set up, which at this point there is no straightforward way to do.

**Comment by jimbolimbo13** [comment]
Looks like it's not as simple as just setting the right Django settings. I mounted /app/babybuddy/babybuddy/settings/base.py to a modified copy in the docker-compose directory and added EMAIL_BACKEND and EMAIL_HOST (I have a local SMTP server in another container, so I don't need a password, TLS, etc).

However, going to request a password reset, throws a 500 error, and after enabling DEBUG, I get this crash dump:

<details>
<summary>Reverse for 'password_reset_confirm' not found. 'password_reset_confirm' is not a valid view function or pattern name</summary>
```Environment:


Request Method: POST
Request URL: https://<babybuddy domain>/password_reset/

Django Version: 4.0.4
Python Version: 3.9.5
Installed Applications:
['api',
 'babybuddy',
 'core',
 'dashboard',
 'reports',
 'axes',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'widget_tweaks',
 'imagekit',
 'storages',
 'import_export',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'babybuddy.middleware.RollingSessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'babybuddy.middleware.UserTimezoneMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'babybuddy.middleware.UserLanguageMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'axes.middleware.AxesMiddleware']


Template error:
In template /usr/lib/python3.9/site-packages/django/contrib/admin/templates/registration/password_reset_email.html, error at line 6
   Reverse for 'password_reset_confirm' not found. 'password_reset_confirm' is not a valid view function or pattern name.
   1 : {% load i18n %}{% autoescape off %}
   2 : {% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}
   3 : 
   4 : {% translate "Please go to the following page and choose a new password:" %}
   5 : {% block reset_link %}
   6 : {{ protocol }}://{{ domain }} {% url 'password_reset_confirm' uidb64=uid token=token %} 
   7 : {% endblock %}
   8 : {% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
   9 : 
   10 : {% translate "Thanks for using our site!" %}
   11 : 
   12 : {% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}
   13 : 
   14 : {% endautoescape %}
   15 : 

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/views.py", line 232, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/views.py", line 245, in form_valid
    form.save(**opts)
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/forms.py", line 343, in save
    self.send_mail(
  File "/usr/lib/python3.9/site-packages/django/contrib/auth/forms.py", line 277, in send_mail
    body = loader.render_to_string(email_template_name, context)
  File "/usr/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3.9/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/usr/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3.9/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.9/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.9/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.9/site-packages/django/template/defaulttags.py", line 52, in render
    output = self.nodelist.render(context)
  File "/usr/lib/python3.9/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.9/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.9/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.9/site-packages/django/template/loader_tags.py", line 54, in render
    result = self.nodelist.render(context)
  File "/usr/lib/python3.9/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.9/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/lib/python3.9/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/lib/python3.9/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3.9/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/urls/resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /password_reset/
Exception Value: Reverse for 'password_reset_confirm' not found. 'password_reset_confirm' is not a valid view function or pattern name.
```
</details>

**Comment by cdubz** [comment]
Thanks for the debugging info. It has probably been like four years since I tested SMTP delivery so it’s entirely possible it’s totally broken 😬
