### ISSUE TITLE
Migration fails for `0028_alter_sleep_options_remove_sleep_napping_sleep_nap` if something in "set_sleep_nap_values" is None

### ISSUE THREAD

**Issue by MrApplejuice** [babybuddy/babybuddy#644]
Regarding the migration `core/migrations/0028_alter_sleep_options_remove_sleep_napping_sleep_nap.py` introduced here:

https://github.com/babybuddy/babybuddy/commit/31a0aa47415c6c3657202361b594c3fa0b171bb6

# How this happened

I am using a semi-persistent database for testing the android app, one that I created about 6 months ago and upgrade (migrate) alongside the babybuddy updates. When I run the migrations now, I am encountering an issue:

~~~~~~
$ gulp migrate
[23:40:03] Using gulpfile ~/code/python/babybuddy/gulpfile.js
[23:40:03] Starting 'migrate'...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, axes, babybuddy, contenttypes, core, dbsettings, sessions
Running migrations:
  Applying babybuddy.0029_alter_settings_language_alter_settings_timezone... OK
  Applying core.0026_alter_feeding_end_alter_feeding_start_and_more... OK
  Applying core.0027_alter_timer_options_remove_timer_duration_and_more... OK
  Applying core.0028_alter_sleep_options_remove_sleep_napping_sleep_nap...Traceback (most recent call last):
  File "/home/paul/code/python/babybuddy/manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/home/paul/.local/share/virtualenvs/babybuddy-bwgPVFMf/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/paul/.local/share/virtualenvs/babybuddy-bwgPVFMf/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/paul/.local/share/virtualenvs/babybuddy-bwgPVFMf/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/paul/.local/share/virtualenvs/babybuddy-bwgPVFMf/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/paul/code/python/babybuddy/babybuddy/management/commands/migrate.py", line 10, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/home/paul/.local/share/virtualenvs/babybuddy-bwgPVFMf/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/home/paul/.local/share/virtualenvs/babybuddy-bwgPVFMf/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/home/paul/.local/share/virtualenvs/babybuddy-bwgPVFMf/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/home/paul/.local/share/virtualenvs/babybuddy-bwgPVFMf/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/home/paul/.local/share/virtualenvs/babybuddy-bwgPVFMf/lib/python3.10/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/paul/.local/share/virtualenvs/babybuddy-bwgPVFMf/lib/python3.10/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/home/paul/.local/share/virtualenvs/babybuddy-bwgPVFMf/lib/python3.10/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/paul/code/python/babybuddy/core/migrations/0028_alter_sleep_options_remove_sleep_napping_sleep_nap.py", line 13, in set_sleep_nap_values
    Sleep.settings.nap_start_min
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.time'
[23:40:05] 'migrate' errored after 1.69 s
[23:40:05] Error: Promise rejected without Error
    at onError (/home/paul/code/python/babybuddy/node_modules/async-done/index.js:49:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
~~~~~~

I assume that this likely should be fixed before the release... I would like to share my example database, looking for a way to upload it.

I assume the `set_sleep_nap_values` function was handwritten? Maybe a bug in there?

**Comment by cdubz** [comment]
Yes it is is handwritten and probably does have a bug 😄 I did some migration tests but I was reluctant to orchestrate a whole automated migration test because time...

Anyway if you have an SQLite DB you can probably just add it to this issue as an attachment?

**Comment by MrApplejuice** [comment]
> Anyway if you have an SQLite DB you can probably just add it to this issue as an attachment?

Was trying to do that, but github does not like the format... but it likes .zip, so I guess that is the one to go for, one sec please!

**Comment by cdubz** [comment]
Plopping here for reference: https://github.com/babybuddy/babybuddy/blob/31a0aa47415c6c3657202361b594c3fa0b171bb6/core/migrations/0028_alter_sleep_options_remove_sleep_napping_sleep_nap.py#L7-L17

**Comment by MrApplejuice** [comment]
[populated_db.sqlite3.zip](https://github.com/babybuddy/babybuddy/files/11456593/populated_db.sqlite3.zip)

There we go... Wanted to double check that no actual "secrets" are in there. Which there should not. Rename the file into `db.sqlite3` and put it in the data folder, see migration fail.

**Comment by cdubz** [comment]
Will give it a test. Thanks for sharing.

The error message and code seem to point to the new _setting_ being empty unexpectedly so I'll be curious if I can indeed reproduce...

**Comment by MrApplejuice** [comment]
I am not using a special settings-file or anything. Might it be that some default value in the dev-settings should be set? I did not drill down to that level yet...

**Comment by cdubz** [comment]
You shouldn't need any changes. Just wondering aloud if the bug is not with the migration itself but with the implementation of the new settings system.

**Comment by MrApplejuice** [comment]
I think I isolated the reason why, but my djnago-foo is a bit rusty, so I do not quite remember how to fix this again:

I deleted and regenerated a "vanilla" 0028-migration and then applied that with `gulp migrate`:

~~~~~~
[00:21:09] Using gulpfile ~/code/python/babybuddy/gulpfile.js
[00:21:09] Starting 'migrate'...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, axes, babybuddy, contenttypes, core, dbsettings, sessions
Running migrations:
  Applying babybuddy.0029_alter_settings_language_alter_settings_timezone... OK
  Applying core.0026_alter_feeding_end_alter_feeding_start_and_more... OK
  Applying core.0027_alter_timer_options_remove_timer_duration_and_more... OK
  Applying core.0028_alter_sleep_options_remove_sleep_napping_sleep_nap... OK
  Applying dbsettings.0001_initial... OK
[00:21:12] Finished 'migrate' after 2.37 s
~~~~~~

As can be seen the initial `dbsettings` migration takes place _after_ the 0028-migration is executed! This is no-good for the hand-written migration that depends on the `dbsettings` table being present already. This will fail for everybody who upgrades from a version that did not use `dbsettings` before the nap-time rework was introduced.. I think that might be quite common...

I remember that it is possible to tell django that there is a dependecy, but I do not remember what machnism is used for that...

**Comment by MrApplejuice** [comment]
Was easy enough to research, actually! Opened PR for the fix.

**Comment by cdubz** [comment]
Interesting... tests pass in the branch but not after merge. Will need to take a closer look.

https://github.com/babybuddy/babybuddy/actions/runs/4953337848/jobs/8860763992

**Comment by MrApplejuice** [comment]
Weird error, might have been a GitHub actions fluke? I ran the actions on my fork this morning and they all passed: https://github.com/MrApplejuice/babybuddy/actions/runs/4956935586/jobs/8867986566

Cannot quite explain this in another way except the scary option: There is some kinds of race condition in the code that cause the tests to fail under certain circumstances. This could explain the "occasional" failure.
