### ISSUE TITLE
Upgrading to 2.0.0 - all credentials invalidated?

### ISSUE THREAD

**Issue by nycntwrkguy** [babybuddy/babybuddy#676]
Hi there, first time writer and big, big fan of the application! I am running the app via the linuxserver/babybuddy container and have the data folder mapped to a folder on my NAS. I have typically upgraded babybuddy minor versions in the 1.x branch without any issue.

I take a backup of the data folder, just in case, stop the old container, pull the image with the new version, create a container off of that, point to the data folder, and everything has gone off smoothly that way.

However, with the 2.0.0 upgrade from 1.1.6, all user account passwords seemed to be invalidated and my API key no longer was recognized, and I locked myself out of all accounts in the course of triple guessing keystrokes. I had to do a data folder restore and bring up the 1.1.6 container.

Is there anything I can provide to assist you in troubleshooting?

**Comment by cdubz** [comment]
Hmmmm. If you’re willing to share your database (either here or over email) I can see if I can reproduce. There is some user related migrations stuff with the 2.0.0 version but can’t quite think how what you’re describing could happen 🤔

**Comment by nycntwrkguy** [comment]
Thank you! I believe I have attached the database you're looking for.

**Comment by nycntwrkguy** [comment]
Is there a way I can contact you directly to send this attachment? I'd prefer not to upload my database publicly on Github if there are sensitive items stored in there (like my son's name, user account information, etc.).

**Comment by cdubz** [comment]
Yep that's fair -- you can email it to babybuddy-676@chris-wells.net

**Comment by cdubz** [comment]
Here I am! Sorry for the delay looking in to this... :grimacing: 

I wasn't able to reproduce the issue with your database. Could you give it another try with the latest version? There is one migration related bug fix in there that _might_ be relevant (though I doubt it).

If you have the same issue you can [create a user from the command line](http://docs.baby-buddy.net/user-guide/managing-users/#creating-a-user-from-the-command-line) (this is what I did to get logged in to your db). Just make sure to set the `--is-staff` flag so you can investigate/unlock/reset passwords for other accounts. From there you should be able to repair the situation.

Let me know how that goes.

**Comment by nycntwrkguy** [comment]
No problem! I just tried it again with the latest version but am running against the same issue. When I attempt to create the new user, I am now seeing:

> No Django settings specified.
Unknown command: 'createuser'
Type 'manage.py help' for usage.

This is after I cd to `/app/www/public` and run the command from that folder.

**Comment by cdubz** [comment]
Argh I really need to update that documentation -- you need to have the `DJANGO_SETTINGS_MODULE` env varaible defined when running the command.

See the note about doing "administrative work" here: http://docs.baby-buddy.net/setup/deployment/#docker

**Comment by nycntwrkguy** [comment]
Thanks for that note! I am now running into this when I tried to do both the clearsessions and the createuser commands:

> root@babybuddy:/app/www/public# python manage.py createuser --username recovery --is-staff
Traceback (most recent call last):
  File "/app/www/public/manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/base.py", line 453, in execute
    self.check()
  File "/lsiopy/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/core/checks/templates.py", line 60, in check_for_template_tags_with_the_same_name
    for module_name, module_path in get_template_tag_modules():
  File "/lsiopy/lib/python3.11/site-packages/django/template/backends/django.py", line 105, in get_template_tag_modules
    for name in get_package_libraries(pkg):
  File "/lsiopy/lib/python3.11/site-packages/django/template/backends/django.py", line 128, in get_package_libraries
    module = import_module(entry[1])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/lsiopy/lib/python3.11/site-packages/qr_code/templatetags/qr_code.py", line 6, in <module>
    from qr_code.qrcode.maker import make_qr_code_with_args, make_qr_code_url_with_args
  File "/lsiopy/lib/python3.11/site-packages/qr_code/qrcode/maker.py", line 12, in <module>
    from qr_code.qrcode.serve import make_qr_code_url
  File "/lsiopy/lib/python3.11/site-packages/qr_code/qrcode/serve.py", line 67, in <module>
    _RANDOM_TOKEN = _make_random_token()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/qr_code/qrcode/serve.py", line 63, in _make_random_token
    url_protection_options = get_url_protection_options()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/qr_code/qrcode/serve.py", line 55, in get_url_protection_options
    options = _get_default_url_protection_options()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/qr_code/qrcode/serve.py", line 23, in _get_default_url_protection_options
    constants.SIGNING_KEY: settings.SECRET_KEY,
                           ^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/django/conf/__init__.py", line 111, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by cdubz** [comment]
Ok so I guess when you do these commands you also need to set the env variables for any other variables in your docker compose configuration.

So assuming the base LSIO config you'll need the environment variables as from: https://github.com/linuxserver/docker-babybuddy/blob/ee3c563e406c7b365910372f98f23d517b702394/root/etc/s6-overlay/s6-rc.d/init-babybuddy-config/run#L17-L22:

```
export \
    DJANGO_SETTINGS_MODULE="babybuddy.settings.base" \
    ALLOWED_HOSTS="${ALLOWED_HOSTS:-*}" \
    TIME_ZONE="${TZ:-UTC}" \
    DEBUG="${DEBUG:-False}" \
    SECRET_KEY="${SECRET_KEY:-$(cat /config/.secretkey)}"
```

**Comment by nycntwrkguy** [comment]
Thank you so much! I've narrowed down the issue to now something going on with my container environment. The QNAP container on this version is not respecting the storage mapping being pointed to the folder. As a result, the database is blank and the /config directory is not reflecting what it should.

**Comment by cdubz** [comment]
Nice! Glad this got ya closer to figuring out the issue. Let me know if I can do anything else to help troubleshoot.

**Comment by nycntwrkguy** [comment]
Thanks so much again! You can close it out. I ended up having to put the full path to the share folder with this version of the container versus the 'friendly' alias. The assist is much appreciated!
