### ISSUE TITLE
Cannot do manual installation: django issue

### ISSUE THREAD

**Issue by quocvjnh** [babybuddy/babybuddy#846]
Hi,

I've been trying to do a manual installation on my Ubuntu VM. After running through every step, I found the below issue in the babybuddy.log file:
```
Traceback (most recent call last):
  File "/var/www/babybuddy/public/./babybuddy/wsgi.py", line 1, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/var/www/babybuddy/public/.venv/lib/python3.10/site-packages/django/core/wsgi.py", line 2, in <module>
    from django.core.handlers.wsgi import WSGIHandler
  File "/var/www/babybuddy/public/.venv/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 5, in <module>
    from django.core.handlers import base
  File "/var/www/babybuddy/public/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 11, in <module>
    from django.urls import get_resolver, set_urlconf
  File "/var/www/babybuddy/public/.venv/lib/python3.10/site-packages/django/urls/__init__.py", line 1, in <module>
    from .base import (
  File "/var/www/babybuddy/public/.venv/lib/python3.10/site-packages/django/urls/base.py", line 6, in <module>
    from django.utils.translation import override
  File "/var/www/babybuddy/public/.venv/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 8, in <module>
    from django.utils.autoreload import autoreload_started, file_changed
  File "/var/www/babybuddy/public/.venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 18, in <module>
    from django.apps import apps
  File "/var/www/babybuddy/public/.venv/lib/python3.10/site-packages/django/apps/__init__.py", line 2, in <module>
    from .registry import apps
  File "/var/www/babybuddy/public/.venv/lib/python3.10/site-packages/django/apps/registry.py", line 13, in <module>
    class Apps:
  File "/var/www/babybuddy/public/.venv/lib/python3.10/site-packages/django/apps/registry.py", line 168, in Apps
    @functools.cache
AttributeError: module 'functools' has no attribute 'cache'
```
My babybuddy.ini file looks like below:
```
[uwsgi]
plugins = python3_plugin.so
plugins-directory = /usr/lib/uwsgi/plugins
project = babybuddy
base_dir = /var/www/babybuddy

chdir = /var/www/babybuddy/public
virtualenv = /var/www/babybuddy/public/.venv
module = babybuddy.wsgi:application
env = DJANGO_SETTINGS_MODULE=babybuddy.settings.production
pythonpath = /var/www/babybuddy/public/.venv/lib/python3.10/site-packages
master = True
vacuum = True
```

Does anyone know what's going wrong with my installation? Thanks for the help!

**Comment by cdubz** [comment]
Your uwsgi configuration differs a bit from the documentation. Is there a reason for this change?

```ini
plugins = python3_plugin.so
plugins-directory = /usr/lib/uwsgi/plugins
```

I infer from this that you built your own Python 3 plugin for UWSGI for some reason? Could you confirm that was built correctly with Python 3.10 libs?

I'll also re-run through the manual steps and see if I find anything that has changed. It has been a while since they were updated.

**Comment by cdubz** [comment]
I have confirmed the manual deploy steps as documented are still working. I made some adjustments to reflect latest changes in Ubuntu 24.04 but otherwise the steps appear to be accurate. I'm going to move to a discussion for support. Please follow up if you are still having trouble.
