### ISSUE TITLE
FILE_UPLOAD_TEMP_DIR not defined when making manage.py makemigration

### ISSUE THREAD

**Issue by Dinth** [babybuddy/babybuddy#857]
Hi. I have been using Baby Buddy for around a year now, but until now i was not aware that there is a process for migration when BB is updated (Watchtower is doing that for me).
Today when looking at BabyBuddy log i found out the following lines:
```
Operations to perform:
  Apply all migrations: admin, auth, authtoken, axes, babybuddy, contenttypes, core, dbsettings, sessions
Running migrations:
  No migrations to apply.
  Your models in app(s): 'babybuddy' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Cache table 'cache_default' already exists.
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2023-07-05 │ 2024-06-30 │ /config/nginx/site-confs/default.conf                                  │
│ 2023-06-24 │ 2023-08-13 │ /config/nginx/ssl.conf                                                 │
│ 2023-04-13 │ 2024-05-27 │ /config/nginx/nginx.conf                                               │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
```

So i connected to the container and tried running makemigration script manually, but im getting the following error:
```
root@19dbfbe7eeb5:/app/www/public#python ./manage.py makemigrations
Traceback (most recent call last):
  File "/app/www/public/./manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/base.py", line 454, in execute
    self.check()
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/core/checks/files.py", line 10, in check_setting_file_upload_temp_dir
    setting = getattr(settings, "FILE_UPLOAD_TEMP_DIR", None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/conf/__init__.py", line 89, in __getattr__
    self._setup(name)
  File "/lsiopy/lib/python3.12/site-packages/django/conf/__init__.py", line 69, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting FILE_UPLOAD_TEMP_DIR, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```
how can i migrate properly?

**Comment by MrApplejuice** [comment]
Do you know if your deployment reconfigures the django settings ins some way? The actual error message you encounter is:

`but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE`. So it sounds like you changed the startup routine or something?

**Comment by Dinth** [comment]
Im using a standard LinuxServer container, havent changed anything on the top of it.

**Comment by cdubz** [comment]
@Dinth were you ever able to make any progress on this? Definitely an odd one… and seemingly having something to do with config files not being found.

**Comment by Dinth** [comment]
Nope, i havent really progressed on this one, to be honest i dont even know where to start

**Comment by cdubz** [comment]
Yeah it’s very bizarre. Are you able to put together repro steps? I’d like to see if I can repro but I don’t really know much about this hosting method.

**Comment by tcassaert** [comment]
I am seeing something similar:
```
root@babybuddy-77478cc9f-7rtk8:/app/www/public# ./manage.py makemigrations
Traceback (most recent call last):
  File "/app/www/public/./manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/base.py", line 454, in execute
    self.check()
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/core/checks/urls.py", line 109, in check_url_settings
    value = getattr(settings, name)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/conf/__init__.py", line 81, in __getattr__
    self._setup(name)
  File "/lsiopy/lib/python3.12/site-packages/django/conf/__init__.py", line 61, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting STATIC_URL, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by cdubz** [comment]
@tcassaert can you share your compose config? In both cases it sounds like `DJANGO_SETTINGS_MODULE` is somehow not being set 🤔And/or the output of `env` in a shell you're trying to run that command from.

In both cases though, `makemigrations` should not need to be run. The migrations are committed to the app. After an upgrade you should need to run `migrate` only.

**Comment by tcassaert** [comment]
My env is the following:
```
DB_PASSWORD=*********************
KUBERNETES_SERVICE_PORT_HTTPS=443
BABYBUDDY_PORT_8000_TCP=tcp://10.43.78.63:8000
KUBERNETES_SERVICE_PORT=443
USE_24_HOUR_TIME_FORMAT=true
PUID=0
BABYBUDDY_PORT_8000_TCP_ADDR=10.43.78.63
HOSTNAME=babybuddy-77478cc9f-6jp9q
S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
BABYBUDDY_SERVICE_PORT=8000
ALLOW_UPLOADS=true
BABYBUDDY_SERVICE_HOST=10.43.78.63
PWD=/app/www/public
DB_ENGINE=django.db.backends.postgresql
DB_PORT=5433
DB_USER=babybuddy
HOME=/root
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
PGID=0
VIRTUAL_ENV=/lsiopy
S6_VERBOSITY=1
S6_STAGE2_HOOK=/init-hook
CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000,https://babybuddy.tcassaert.com
BABYBUDDY_PORT_8000_TCP_PROTO=tcp
TERM=xterm
DB_HOST=192.168.1.100
SHLVL=2
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
DB_NAME=babybuddy
PS1=$(whoami)@$(hostname):$(pwd)\$
BABYBUDDY_PORT_8000_TCP_PORT=8000
TIME_ZONE=Europe/Brussels
KUBERNETES_SERVICE_HOST=10.43.0.1
LSIO_FIRST_PARTY=true
KUBERNETES_PORT=tcp://10.43.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
BABYBUDDY_PORT=tcp://10.43.78.63:8000
_=/usr/bin/env
OLDPWD=/
```

As you can see, I'm running on Kubernetes, so I don't have a compose file.

About the need to only run `migrate`, the logs told me something else:
```
Operations to perform:
  Apply all migrations: admin, auth, authtoken, axes, babybuddy, contenttypes, core, dbsettings, sessions
Running migrations:
  No migrations to apply.
  Your models in app(s): 'babybuddy' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
  ```

**Comment by cdubz** [comment]
@tcassaert those looks like normal logs for the `migrate` command (sometimes the migrations are behind or not synced and that's OK).

You should still be able to make them, but you shouldn't _have_ to.

If you are manually running a command, the `DJANGO_SETTINGS_MODULE` env needs to be set. I believe in the case of LSIO it would be `DJANGO_SETTINGS_MODULE=babybuddy.settings.base`.

**Comment by Dinth** [comment]
Thanks for the above. Now im getting this: 
```
root@19dbfbe7eeb5:/app/www/public#DJANGO_SETTINGS_MODULE=babybuddy.settings.base ./manage.py makemigrations
Traceback (most recent call last):
  File "/lsiopy/lib/python3.12/site-packages/django/template/utils.py", line 69, in __getitem__
    return self._engines[alias]
           ~~~~~~~~~~~~~^^^^^^^
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/www/public/./manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/base.py", line 454, in execute
    self.check()
  File "/lsiopy/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/core/checks/templates.py", line 10, in check_templates
    for engine in engines.all():
                  ^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/utils.py", line 94, in all
    return [self[alias] for alias in self]
            ~~~~^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/utils.py", line 85, in __getitem__
    engine = engine_cls(params)
             ^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/backends/django.py", line 26, in __init__
    options["libraries"] = self.get_templatetag_libraries(libraries)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/backends/django.py", line 88, in get_templatetag_libraries
    libraries = get_installed_libraries()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/backends/django.py", line 163, in get_installed_libraries
    module_name: full_name for module_name, full_name in get_template_tag_modules()
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/backends/django.py", line 151, in get_template_tag_modules
    for name in get_package_libraries(pkg):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/backends/django.py", line 174, in get_package_libraries
    module = import_module(entry[1])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/lsiopy/lib/python3.12/site-packages/qr_code/templatetags/qr_code.py", line 6, in <module>
    from qr_code.qrcode.maker import make_qr_code_with_args, make_qr_code_url_with_args
  File "/lsiopy/lib/python3.12/site-packages/qr_code/qrcode/maker.py", line 13, in <module>
    from qr_code.qrcode.serve import make_qr_code_url
  File "/lsiopy/lib/python3.12/site-packages/qr_code/qrcode/serve.py", line 67, in <module>
    _RANDOM_TOKEN = _make_random_token()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/qr_code/qrcode/serve.py", line 63, in _make_random_token
    url_protection_options = get_url_protection_options()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/qr_code/qrcode/serve.py", line 55, in get_url_protection_options
    options = _get_default_url_protection_options()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/qr_code/qrcode/serve.py", line 23, in _get_default_url_protection_options
    constants.SIGNING_KEY: settings.SECRET_KEY,
                           ^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/conf/__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
root@19dbfbe7eeb5:/app/www/public#
```

This being said - if i dont need to run makemigrations then i guess i unnecessarily panicked and the issue can be closed?

**Comment by cdubz** [comment]
> This being said - if i dont need to run makemigrations then i guess i unnecessarily panicked and the issue can be closed?

Yes, I agree. It seems odd, but should not impact anything.
