### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by Znerox** [babybuddy/babybuddy#892]
I'm suddenly getting this error message, no change done on my side. How to enable debug mode to troubleshoot this? I've tried setting "DEBUG=True" as a parameter to the container. Can't do anything in the settings since I can't access the webpage.

**Comment by Znerox** [comment]
Enabled debug mode.
`KeyError at /children/NAME/dashboard/`
`Request Method: 	GET
Request URL: 	http://IP:8000/children/NAME/dashboard/
Django Version: 	5.1
Exception Type: 	KeyError
Exception Value: 	

7

Exception Location: 	/app/www/public/dashboard/templatetags/cards.py, line 86, in card_diaperchange_types
Raised during: 	dashboard.views.ChildDashboard
Python Executable: 	/lsiopy/bin/python3
Python Version: 	3.12.7
Python Path: 	

['/app/www/public',
 '/lsiopy/bin',
 '/usr/lib/python312.zip',
 '/usr/lib/python3.12',
 '/usr/lib/python3.12/lib-dynload',
 '/lsiopy/lib/python3.12/site-packages',
 '/lsiopy/lib/python3.12/site-packages/odf',
 '/lsiopy/lib/python3.12/site-packages/odf',
 '/lsiopy/lib/python3.12/site-packages/odf',
 '/lsiopy/lib/python3.12/site-packages/odf',
 '/lsiopy/lib/python3.12/site-packages/odf',
 '/lsiopy/lib/python3.12/site-packages/odf',
 '/lsiopy/lib/python3.12/site-packages/odf']`

Error during template rendering
In template /app/www/public/dashboard/templates/dashboard/child.html, error at line 28
` <div class="col-sm-6 col-lg-4">{% card_diaperchange_types object %}</div>`

**Comment by Moraziel** [comment]
had the same error yesterday, it solved itself today. 
Any chance it could be an edge effect due to the DST time change of sunday ? That's the only thing I can think of.

**Comment by Znerox** [comment]
I just checked, the issue is solved for me as well.

**Comment by boszme** [comment]
Yes this is related to the DST BabyBuddy is extremely picky on the timezones, I've ran into similar issues while traveling and changed timezones compared to BabyBuddy's location.

While we wait for a fix a workaround is to set `Hide data older than` to 1 day and as time passes it can be increased, but never use `show all data` until it is fixed. 

This bug affects the main dashboard, the remaining part of the application is still usable. Unfortunately there is nothing in the logs even on `DEBUG` loglevel..

**Comment by anuneo** [comment]
I am unfortunately facing this problem since the past few hours. The suggested workaround, did not solve the problem for me. 

> While we wait for a fix a workaround is to set `Hide data older than` to 1 day and as time passes it can be increased, but never use `show all data` until it is fixed.

Any other ideas?

**Comment by pierre-vo** [comment]
Same here, `Hide data older than 1day` does not fix it.

**Comment by lukasMega** [comment]
<details><summary>➕1️⃣  I have the same error:</summary>

```
Environment:


Request Method: GET
Request URL: http://192.168.88.5:1904/children/mar%C3%ADnka-m/dashboard/

Django Version: 5.1
Python Version: 3.12.7
Installed Applications:
['api',
 'babybuddy.apps.BabyBuddyConfig',
 'core.apps.CoreConfig',
 'corsheaders',
 'dashboard',
 'reports',
 'axes',
 'django_filters',
 'rest_framework',
 'rest_framework.authtoken',
 'widget_tweaks',
 'imagekit',
 'storages',
 'import_export',
 'qr_code',
 'dbsettings',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'babybuddy.middleware.RollingSessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'babybuddy.middleware.UserTimezoneMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'babybuddy.middleware.UserLanguageMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'axes.middleware.AxesMiddleware',
 'babybuddy.middleware.HomeAssistant']


Template error:
In template /app/www/public/dashboard/templates/dashboard/child.html, error at line 28
   7
   18 :         <div class="col-sm-6 col-lg-4">{% card_feeding_last object %}</div>
   19 :         <div class="col-sm-6 col-lg-4">{% card_diaperchange_last object %}</div>
   20 :         <div class="col-sm-6 col-lg-4">{% card_pumping_last object %}</div>
   21 :         <div class="col-sm-6 col-lg-4">{% card_sleep_last object %}</div>
   22 :         <div class="col-sm-6 col-lg-4">{% card_feeding_last_method object %}</div>
   23 :         <div class="col-sm-6 col-lg-4">{% card_feeding_recent object %}</div>
   24 :         <div class="col-sm-6 col-lg-4">{% card_statistics object %}</div>
   25 :         <div class="col-sm-6 col-lg-4">{% card_sleep_recent object %}</div>
   26 :         <div class="col-sm-6 col-lg-4">{% card_sleep_naps_day object %}</div>
   27 :         <div class="col-sm-6 col-lg-4">{% card_tummytime_day object %}</div>
   28 :         <div class="col-sm-6 col-lg-4"> {% card_diaperchange_types object %} </div>
   29 :         <div class="col-sm-6 col-lg-4">{% card_breastfeeding object %}</div>
   30 :     </div>
   31 : {% endblock %}
   32 : {% block javascript %}
   33 :     {% if user.settings.dashboard_refresh_rate %}
   34 :         <script type="application/javascript">
   35 :             BabyBuddy.Dashboard.watch('dashboard-child', {{ user.settings.dashboard_refresh_rate_milliseconds }});
   36 :         </script>
   37 :     {% else %}
   38 :         <script type="application/javascript">BabyBuddy.Dashboard.watch('dashboard-child', false);</script>


Traceback (most recent call last):
  File "/lsiopy/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.12/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/www/public/dashboard/templatetags/cards.py", line 86, in card_diaperchange_types
    stats[key]["changes"] += 1
    ^^^^^^^^^^

Exception Type: KeyError at /children/marínka-m/dashboard/
Exception Value: 7
```

</details>

- dashboard is not working
- tried to change various settings (including `Hide data older than 1day`) - no change
- tried to use older docker image
- I have not changed time / timezone settings in past, I have never touch such things
- nothing helps

**Comment by anuneo** [comment]
I created a temporary `child`. This helps a little. Atleast the direct error is not seen while opening the app.

**Comment by Znerox** [comment]
This is weird. It started working yesterday, now it's broken again. As others said, it's only the dashboard that is broken.

**Comment by DJFliX** [comment]
My wife just told me that our Babybuddy deployment wasn't working. Strangely enough I couldn't reproduce the issue. Looks like the issue is only affecting her account (`admin`) but not mine (`flix`). I've set her account to `Hide data older than to 1 day` but no dice.

**Comment by cdubz** [comment]
This specific issue will be fixed in the next release. Continuing to track others over at #893.
